// <auto-generated />
using System;
using Hr_Vacancy_Managment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hr_Vacancy_Managment.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240830181031_vacancy")]
    partial class vacancy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hr_Vacancy_Managment.Models.Department", b =>
                {
                    b.Property<int>("Department_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Department_ID"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Department_Status")
                        .HasColumnType("int");

                    b.HasKey("Department_ID");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Hr_Vacancy_Managment.Models.Employee", b =>
                {
                    b.Property<int>("Employee_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Employee_ID"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Depart_ID")
                        .HasColumnType("int");

                    b.Property<string>("Employee_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employee_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Employee_Status")
                        .HasColumnType("int");

                    b.HasKey("Employee_ID");

                    b.HasIndex("Depart_ID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Hr_Vacancy_Managment.Models.Vacancy", b =>
                {
                    b.Property<int>("Vacancy_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Vacancy_ID"));

                    b.Property<DateTime>("Date_Of_Creation")
                        .HasColumnType("datetime2");

                    b.Property<int>("Depart_ID")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentsDepartment_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Last_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number_Of_Jobs_Under_Vacancy")
                        .HasColumnType("int");

                    b.Property<int>("Owned_By")
                        .HasColumnType("int");

                    b.Property<string>("Vacancy_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vacancy_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vacancy_Status")
                        .HasColumnType("int");

                    b.Property<string>("Vacancy_Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Vacancy_ID");

                    b.HasIndex("DepartmentsDepartment_ID");

                    b.ToTable("Vacancy");
                });

            modelBuilder.Entity("Hr_Vacancy_Managment.Models.Employee", b =>
                {
                    b.HasOne("Hr_Vacancy_Managment.Models.Department", "department")
                        .WithMany("employees")
                        .HasForeignKey("Depart_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("Hr_Vacancy_Managment.Models.Vacancy", b =>
                {
                    b.HasOne("Hr_Vacancy_Managment.Models.Department", "Departments")
                        .WithMany("Vacancy")
                        .HasForeignKey("DepartmentsDepartment_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("Hr_Vacancy_Managment.Models.Department", b =>
                {
                    b.Navigation("Vacancy");

                    b.Navigation("employees");
                });
#pragma warning restore 612, 618
        }
    }
}
