// <auto-generated />
using System;
using Hr_Vacancy_Managment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hr_Vacancy_Managment.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hr_Vacancy_Managment.Models.Applicant", b =>
                {
                    b.Property<int>("Applicant_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Applicant_ID"));

                    b.Property<string>("Applicant_CV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicant_Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Applicant_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Applicant_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicant_Phone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("Applicant_Status")
                        .HasColumnType("int");

                    b.Property<string>("Applied_For")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Applicant_ID");

                    b.ToTable("Applicant");
                });

            modelBuilder.Entity("Hr_Vacancy_Managment.Models.Applicant_Vacancy", b =>
                {
                    b.Property<int>("Applicant_Vacancy_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Applicant_Vacancy_ID"));

                    b.Property<int?>("App_Vac_Status")
                        .HasColumnType("int");

                    b.Property<int>("Applicant_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Applied_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Interviewer_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interviewer_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Scheduled_Interview_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Vacancy_ID")
                        .HasColumnType("int");

                    b.HasKey("Applicant_Vacancy_ID");

                    b.HasIndex("Applicant_ID");

                    b.HasIndex("Vacancy_ID");

                    b.ToTable("Applicant_Vacancy");
                });

            modelBuilder.Entity("Hr_Vacancy_Managment.Models.Department", b =>
                {
                    b.Property<int>("Department_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Department_ID"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Department_Status")
                        .HasColumnType("int");

                    b.HasKey("Department_ID");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Hr_Vacancy_Managment.Models.Employee", b =>
                {
                    b.Property<int>("Employee_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Employee_ID"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Depart_ID")
                        .HasColumnType("int");

                    b.Property<string>("Employee_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employee_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employee_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employee_Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Employee_Status")
                        .HasColumnType("int");

                    b.HasKey("Employee_ID");

                    b.HasIndex("Depart_ID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Hr_Vacancy_Managment.Models.User", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_ID"));

                    b.Property<string>("User_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("User_Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("user_status")
                        .HasColumnType("int");

                    b.HasKey("User_ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Hr_Vacancy_Managment.Models.Vacancy", b =>
                {
                    b.Property<int>("Vacancy_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Vacancy_ID"));

                    b.Property<DateTime>("Date_Of_Creation")
                        .HasColumnType("datetime2");

                    b.Property<int>("Depart_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Last_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number_Of_Jobs_Under_Vacancy")
                        .HasColumnType("int");

                    b.Property<string>("Owned_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Timing")
                        .HasColumnType("int");

                    b.Property<string>("Vacancy_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vacancy_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vacancy_Status")
                        .HasColumnType("int");

                    b.Property<string>("Vacancy_Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("salary")
                        .HasColumnType("int");

                    b.HasKey("Vacancy_ID");

                    b.HasIndex("Depart_ID");

                    b.ToTable("Vacancy");
                });

            modelBuilder.Entity("Hr_Vacancy_Managment.Models.Applicant_Vacancy", b =>
                {
                    b.HasOne("Hr_Vacancy_Managment.Models.Applicant", "applicant")
                        .WithMany()
                        .HasForeignKey("Applicant_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hr_Vacancy_Managment.Models.Vacancy", "vacancy")
                        .WithMany()
                        .HasForeignKey("Vacancy_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("applicant");

                    b.Navigation("vacancy");
                });

            modelBuilder.Entity("Hr_Vacancy_Managment.Models.Employee", b =>
                {
                    b.HasOne("Hr_Vacancy_Managment.Models.Department", "department")
                        .WithMany("employees")
                        .HasForeignKey("Depart_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("Hr_Vacancy_Managment.Models.Vacancy", b =>
                {
                    b.HasOne("Hr_Vacancy_Managment.Models.Department", "Departments")
                        .WithMany("Vacancy")
                        .HasForeignKey("Depart_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("Hr_Vacancy_Managment.Models.Department", b =>
                {
                    b.Navigation("Vacancy");

                    b.Navigation("employees");
                });
#pragma warning restore 612, 618
        }
    }
}
